### PR TITLE
Implement resolution buttons in the preferences page

### PR DESCRIPTION
**Pull request by emanuele-f**
Please check the min and max values where "TODO check min/max" is specified

### CODE REVIEW

**Comment by simonemainardi** [comment]
empty values are allowed and saved to redis as NaNs

image

```
127.0.0.1:6379> get ntopng.prefs.local_host_max_idle
"NaN"
```

prevent this behavior

**Comment by emanuele-f** [comment]
According to variable names in code, it seems like empty fields should restore default value, but this seems broken since the default parameter passed is not really the default but the previous value of the field. What's the intented behaviour?

**Comment by simonemainardi** [comment]
prevent empty fields from being saved

**Comment by simonemainardi** [comment]
image

**Comment by simonemainardi** [comment]
merged manually after test and extra works. Thank you.

**Pull request closed without merging**
