### PR TITLE
Simple / Advanced preferences and input fields changes

### PR DESCRIPTION
**Pull request by emanuele-f**
Changes
- Validate ldap format
- Validate google API key format
- Make some input fields larger
- Unified menu code into the table `menu_subpages`
- Advanced/Simple options toggle button affecting menu entries and single preferences

### CODE REVIEW

**Comment by simonemainardi** [comment]
accepted after test and changes. Thank you. Please review this

image

corners of the input fields are smoothed on the left and squared on the right.

thank you

**Comment by simonemainardi** [comment]
please, also check tab "On-Disk Timeseries" that no longer have a save button when advances prefs is diabled. Due to this issue I didn't merge the branch in the main dev. Please review.

**Comment by emanuele-f** [comment]
Changes implemented, please check out

**Comment by simonemainardi** [comment]
time selectors no longer work and values are always saved as "Secs"

image

**Pull request merged**
