### PR TITLE
Latest jp.lua update request

### PR DESCRIPTION
**Pull request by Yoshihiro-jp**
I create the jp.lua for the latest ntopng nightly build version.

### CODE REVIEW

**Comment by lucaderi** [comment]
Can you please resolve the conflict and sign this https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md

**Comment by lucaderi** [comment]
@Yoshihiro-jp Any news?

**Comment by Yoshihiro-jp** [comment]
> @Yoshihiro-jp Any news?

Ｉ am not so familiar with the github. I thought that I already fixed the conflicts. What should I do next?

regards,

**Comment by Yoshihiro-jp** [comment]
@lucaderi 
Should I do something? If so kindly tell me please.

regards,
Yoshihiro

**Pull request merged**
