### PR TITLE
Localize title of columns on table in hosts_stats

### PR DESCRIPTION
**Pull request by TakayukiOnodera**
dumpFile API call is replaced with code that should be dumped by API.

### CODE REVIEW

**Comment by emanuele-f** [comment]
Thank you!

**Comment by simonemainardi** [comment]
thank yu!,

BTW , can files httpdocs/inc/host_stats_top.inc and httpdocs/inc/host_stats_bottom.inc be removed after this ?

**Comment by emanuele-f** [comment]
Removed in 21d0e55dd0c43ff22a55c153de1aebd2ddb71c4d

**Comment by TakayukiOnodera** [comment]
No, both include files are still referenced from other lua files. I will remove these include files when I have finished to do similar work for other files.

**Pull request merged**
