### PR TITLE
Historical explorer

### PR DESCRIPTION
**Pull request by emanuele-f**
Requires pro branch

### CODE REVIEW

**Comment by emanuele-f** [comment]
Wait, there is something to fix before merge.

**Comment by emanuele-f** [comment]
Fix integrated, please check out the 'TODO this could lead to long queries that cannot be aborted in pages where "Flows Summary" tab is not active'

**Comment by emanuele-f** [comment]
Ready to code review

**Comment by lucaderi** [comment]
@simonemainardi Please approve it or we close for inactivity.

**Comment by simonemainardi** [comment]
closing to avoid unnecessary queries to MySQL when browsing charts

**Pull request closed without merging**
