### PR TITLE
New user activities and filters

### PR DESCRIPTION
**Pull request by emanuele-f**

### CODE REVIEW

**Comment by lucaderi** [comment]
Thank you

**Comment by lucaderi** [comment]
I have made this fix https://github.com/ntop/ntopng/commit/ac2db07d4c0afb2e586f1fe3f20d12c18d8d245c
to avoid a crash. Please check the code logic.

**Comment by lucaderi** [comment]
However there is still a bug you need to fix

23/Aug/2016 09:50:40 [NetworkInterface.cpp:3995] WARNING: Error while executing flowProtocolDetected [rc=2][...s/deri/network/ntopng/scripts/callbacks/flowactivity.lua:277: bad argument 1 to 'unpack' (table expected, got nil)]

**Comment by emanuele-f** [comment]
ac2db07 it's ok, for the other bug there is a typo error in line 228 "detaults". Sorry for these.

**Pull request merged**
