### PR TITLE
Updated jp.lua

### PR DESCRIPTION
**Pull request by Yoshihiro-jp**
I added a lot of missing translation from en.lua.

### CODE REVIEW

**Comment by cardigliano** [comment]
@Yoshihiro-jp it seems the version you edited was not up to date as many lines were missing, could you resolve the conflicts please?

**Comment by Yoshihiro-jp** [comment]
> @Yoshihiro-jp it seems the version you edited was not up to date as many lines were missing, could you resolve the conflicts please?

I think because there are so many added lines.... 
Is it okay for me to send the jp.lua to you?
Since I am not familiar with the github....

regards,
Yoshihiro

**Comment by cardigliano** [comment]
The way you sent the PR is fine, you just need to update your branch. Sending me a .lua is also fine (but you will not appear as contributor), as you prefer.

**Comment by Yoshihiro-jp** [comment]
> The way you sent the PR is fine, you just need to update your branch. Sending me a .lua is also fine (but you will not appear as contributor), as you prefer.

I don't have to be appeared as a contributor. I sent it to you via email. Kindly commit it.

regards,
Yoshihiro

**Comment by cardigliano** [comment]
Pushed. Thank you.

**Pull request closed without merging**
