### PR TITLE
Force default admin password change

### PR DESCRIPTION
**Pull request by emanuele-f**
Implements #1153

screenshot at 2017-04-27 21-17-43

### CODE REVIEW

**Comment by simonemainardi** [comment]
@ValentinaViscarelli can you please check if LDAP auth remains valid with this pull request? 

Thank you

**Comment by emanuele-f** [comment]
Note: the current behaviour with LDAP should be this: if a user selected the LDAP auth but has the default admin password set, then the password change dialog will appear after the LDAP auth takes place.

Note: after being forced to change the default admin password, the user can change it back to the default password from the ntopng user preferences. This is intentional as I think the user should have the possibility to do this.

**Comment by ValentinaViscarelli** [comment]
@simonemainardi and @emanuele-f 
The "password change dialog" appears just for local authentication.

- If you have "local" authentication set then "password change dialog" appears properly.
- If you have "local/ldap" authentication then set the "password change dialog" appears just for local authentication. That means you can authenticate properly with ldap and "password change dialog" doesn't appear.only
- If you have "ldap" authentication set then the "password change dialog" doesn't appear after you have logged into account with ldap.

I don't know that should be the right behavior but this is not true:

_"Note: the current behaviour with LDAP should be this: if a user selected the LDAP auth but has the default admin password set, then the password change dialog will appear after the LDAP auth takes place."_

Let me know if I have to do other tests.

**Comment by emanuele-f** [comment]
@ValentinaViscarelli thank you for your test. But I think the behaviour you get with ldap and local/ldap is not actually correct, can you please try the following steps and report your result?
1) reset redis `redis-cli flushall`
2) login into ntopng and change the password from the dialog
3) go to the users and change admin password back to "admin"
4) go to the preferences and set ldap auth only with your credentials
5) logout from ntopng
6) run `redis-cli del ntopng.prefs.admin_password_changed`.
7) login into ntopng with ldap
8) you should get the password reset dialog appear, is this correct?

**Comment by ValentinaViscarelli** [comment]
@emanuele-f 
Steps from 1 to 7 -> SUCCESS
Step 8 -> FAILED (you don't get password reset dialog but you log on system directly).

**Comment by emanuele-f** [comment]
Got it, thank you for your test.

**Pull request merged**
